[env]
CC = { value = "scratch/mcn97/projects/better-search-rag-rust/.venv/bin/x86_64-conda-linux-gnu-cc", relative = false }
CXX = { value = "scratch/mcn97/projects/better-search-rag-rust/.venv/bin/x86_64-conda-linux-gnu-c++", relative = false }
OMPI_CC = { value = "scratch/mcn97/projects/better-search-rag-rust/.venv/bin/x86_64-conda-linux-gnu-cc", relative = false }
OMPI_CXX = { value = "scratch/mcn97/projects/better-search-rag-rust/.venv/bin/x86_64-conda-linux-gnu-c++", relative = false }

[build]
rustflags = [
    "-L",
    "native=scratch/mcn97/projects/better-search-rag-rust/.venv/lib",
    "-C",
    "link-arg=-Wl,-rpath,scratch/mcn97/projects/better-search-rag-rust/.venv/lib",
]
