[env]
CC = { value = ".venv/bin/x86_64-conda-linux-gnu-cc", relative = true }
CXX = { value = ".venv/bin/x86_64-conda-linux-gnu-c++", relative = true }
OMPI_CC = { value = ".venv/bin/x86_64-conda-linux-gnu-cc", relative = true }
OMPI_CXX = { value = ".venv/bin/x86_64-conda-linux-gnu-c++", relative = true }

[build]
rustflags = [
    "-L",
    "native=./.venv/lib",
    "-C",
    "link-arg=-Wl,-rpath,./.venv/lib",
]
